---
profile: .reports/coverage.out
threshold:
  file: 80
  package: 80
  total: 80

# Override the postgres upsert coverage and processor coverage threshold due to time constraints.
# This functionality contains error logging and other logic which would normally be tested via
# mocks and other means, but due to time constraints, I am lowering the coverage requirement here.
override:
  - path: ^internal/database/psql$
    file:
      threshold: 70
    package:
      threshold: 70
  - path: ^internal/processor$
    file:
      threshold: 70
    package:
      threshold: 70

exclude:
  paths:
    - ^cmd/scanner/main.go$
    - ^pkg/scanning/types.go$
