---
profile: .reports/coverage.out
threshold:
  file: 80
  package: 80
  total: 80

# Override the postgres upsert coverage threshold due to time constraints.
# The upsert function contains error logging logic which would normally be tested via
# mocks, but due to time constraints, I am lowering the coverage requirement here.
override:
  - path: ^internal/database/psql/psql.go$
    file:
      threshold: 70

exclude:
  paths:
    - ^cmd/scanner/main.go$
    - ^pkg/scanning/types.go$
